services:
    auth.doctrine_manager:
        class: AuthBundle\Authentication\DoctrineManager
        calls:
            - [setManager, ["@service_container"]]

    auth.login:
        class: AuthBundle\Authentication\Authentication
        arguments: ["@bs.rapi.request"]
        parent: auth.doctrine_manager
        calls:
            - [setCurrentUserManager, ["%auth.current_user%"]]

    auth.command.role_command:
        class: AuthBundle\Command\RoleCommand
        arguments: ["@auth.doctrine_manager", "@auth.role_service"]
        tags:
            -  { name: console.command }

    auth.command.access_command:
        class: AuthBundle\Command\AccessCommand
        arguments: ["@auth.doctrine_manager", "@auth.access_service"]
        tags:
            -  { name: console.command }

    auth.command.user_command:
        class: AuthBundle\Command\UserCommand
        arguments: ["@auth.user_service"]
        tags:
            -  { name: console.command }

    auth.role_service:
        class: AuthBundle\Entity\Role\RoleService
        parent: auth.doctrine_manager
        calls:
            - [init]

    auth.access_service:
        class: AuthBundle\Entity\Access\AccessService
        parent: auth.doctrine_manager
        calls:
            - [init]

    auth.user_service:
        class: AuthBundle\Entity\User\UserService
        parent: auth.doctrine_manager
        arguments: ["@auth.token_service", "%secret%"]
        calls:
            - [init]

    auth.token_service:
        class: AuthBundle\Entity\Token\TokenService
        parent: auth.doctrine_manager
        calls:
            - [init]
